name: Makis Otman
description: A blog documenting my journey towards programming enlightment.
url: http://0.0.0.0:4000
environment: development
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
rouge: true
